spring:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ec-201804a
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp